In [7]:
import numpy as np
import h5py

matrix1 = np.random.random(size =(1000,1000))
matrix2 = np.random.random(size =(10000, 100))

with h5py.File('/home/ivanwilliam/Desktop/hdf5_data.h5', 'w') as hdf:
    hdf.create_dataset('dataset1', data=matrix1)
    hdf.create_dataset('dataset2', data=matrix2)

In [12]:
with h5py.File('/home/ivanwilliam/Desktop/hdf5_data.h5', 'r') as hdf:
    ls = list(hdf.keys())
    print('List of dataset in this file: \n', ls)
    data1 = hdf.get('dataset1')
    dataset1=np.array(data1)
    print('Shape of dataset1 \n', dataset1.shape)
    data2 = hdf.get('dataset2')
    dataset2=np.array(data2)
    print('Shape of dataset1 \n', dataset2.shape)

List of dataset in this file: 
 ['dataset1', 'dataset2']
Shape of dataset1 
 (1000, 1000)
Shape of dataset1 
 [[0.43721213 0.11608867 0.26125643 ... 0.09123152 0.59257203 0.57146432]
 [0.39282298 0.50018906 0.68202135 ... 0.503505   0.18088071 0.91852733]
 [0.26638647 0.3226436  0.39459731 ... 0.89566866 0.66582239 0.44450223]
 ...
 [0.85558527 0.90334738 0.58702112 ... 0.47227278 0.42392087 0.63108292]
 [0.57549252 0.45999212 0.7381569  ... 0.65766249 0.4936572  0.01441738]
 [0.38470554 0.76628143 0.42503342 ... 0.59048422 0.36020211 0.40200544]]
Shape of dataset1 
 (10000, 100)


In [13]:
data1

<Closed HDF5 dataset>

In [14]:
dataset1

array([[0.43721213, 0.11608867, 0.26125643, ..., 0.09123152, 0.59257203,
        0.57146432],
       [0.39282298, 0.50018906, 0.68202135, ..., 0.503505  , 0.18088071,
        0.91852733],
       [0.26638647, 0.3226436 , 0.39459731, ..., 0.89566866, 0.66582239,
        0.44450223],
       ...,
       [0.85558527, 0.90334738, 0.58702112, ..., 0.47227278, 0.42392087,
        0.63108292],
       [0.57549252, 0.45999212, 0.7381569 , ..., 0.65766249, 0.4936572 ,
        0.01441738],
       [0.38470554, 0.76628143, 0.42503342, ..., 0.59048422, 0.36020211,
        0.40200544]])

In [21]:
f = h5py.File('/home/ivanwilliam/Desktop/hdf5_data.h5', 'r') 
ls = list(f.keys())
data1 = f.get('dataset1')
dataset1=np.array(data1)
print('Shape of dataset1 \n', dataset1.shape)
f.close()

Shape of dataset1 
 (1000, 1000)


In [17]:
ls

['dataset1', 'dataset2']

Shape of dataset1 
 (1000, 1000)


In [ ]:
matrix1 = np.random.random(size =(1000,1000))
matrix2 = np.random.random(size =(10000, 100))